import { useState } from "react";
import { motion } from "framer-motion";
import { AppLayout } from "@/components/layout";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { 
  XOctagon, 
  CheckCircle2, 
  Info, 
  Search, 
  ShieldAlert, 
  Briefcase, 
  Wallet, 
  Building, 
  FileSignature,
  ArrowRight
} from "lucide-react";

export default function Output() {
  const [dialogOpen, setDialogOpen] = useState(false);

  const csData = [
    { name: "Character", icon: ShieldAlert, score: "Low", desc: "Active litigations flagged", color: "text-red-400", bg: "bg-red-400/10", border: "border-red-400/20" },
    { name: "Capacity", icon: Briefcase, score: "Moderate", desc: "40% factory utilization", color: "text-amber-400", bg: "bg-amber-400/10", border: "border-amber-400/20" },
    { name: "Capital", icon: Wallet, score: "Strong", desc: "Healthy GST & ITR flows", color: "text-emerald-400", bg: "bg-emerald-400/10", border: "border-emerald-400/20" },
    { name: "Collateral", icon: Building, score: "Strong", desc: "Fully backed by property", color: "text-emerald-400", bg: "bg-emerald-400/10", border: "border-emerald-400/20" },
    { name: "Conditions", icon: FileSignature, score: "Poor", desc: "Sector headwinds & RBI norms", color: "text-red-400", bg: "bg-red-400/10", border: "border-red-400/20" },
  ];

  return (
    <AppLayout>
      <motion.div 
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5 }}
        className="space-y-8 max-w-5xl mx-auto pb-20"
      >
        <div className="text-center space-y-2 mt-4">
          <Badge variant="outline" className="mb-4 bg-primary/5 text-primary border-primary/20 px-4 py-1.5 uppercase tracking-widest text-[10px]">
            The Recommendation Engine
          </Badge>
          <h1 className="text-4xl font-bold font-display text-gradient">Credit Appraisal Memo</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Final automated decision output generated by fusing structured models, VLM parsing, and dynamic web intelligence.
          </p>
        </div>

        {/* Top: Final Decision Gauge/Banner */}
        <motion.div 
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.2 }}
        >
          <Card className="relative overflow-hidden border-red-500/30 bg-gradient-to-br from-red-500/10 via-black to-black shadow-[0_0_50px_rgba(239,68,68,0.15)]">
            <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-red-600 to-red-400"></div>
            <CardContent className="p-8 sm:p-12 text-center">
              <div className="flex flex-col items-center justify-center">
                <div className="w-20 h-20 rounded-full bg-red-500/20 flex items-center justify-center mb-6 border border-red-500/30 shadow-[0_0_30px_rgba(239,68,68,0.3)]">
                  <XOctagon className="w-10 h-10 text-red-500" />
                </div>
                <h2 className="text-3xl sm:text-5xl font-black font-display tracking-tight text-white mb-4 drop-shadow-md">
                  RECOMMENDATION: <span className="text-red-500">REJECT</span>
                </h2>
                
                <div className="flex flex-wrap items-center justify-center gap-4 mt-4">
                  <div className="px-6 py-3 rounded-xl bg-white/5 border border-white/10 backdrop-blur-md">
                    <p className="text-xs text-muted-foreground uppercase tracking-widest font-semibold mb-1">Suggested Limit</p>
                    <p className="text-2xl font-bold text-white/50 line-through decoration-red-500/50">₹5.00 Cr</p>
                  </div>
                  <div className="px-6 py-3 rounded-xl bg-white/5 border border-white/10 backdrop-blur-md">
                    <p className="text-xs text-muted-foreground uppercase tracking-widest font-semibold mb-1">Base Rate</p>
                    <p className="text-2xl font-bold text-white/50">N/A</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Middle: Five Cs Cards */}
        <div className="space-y-4">
          <h3 className="text-lg font-semibold text-white/90 px-1">Automated 5C Matrix</h3>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            {csData.map((item, i) => (
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 + (i * 0.1) }}
                key={item.name}
              >
                <Card className={`glass-panel h-full border ${item.border} ${item.bg} hover-elevate`}>
                  <CardContent className="p-5 flex flex-col items-center text-center h-full">
                    <item.icon className={`w-6 h-6 mb-3 ${item.color}`} />
                    <h4 className="font-display font-bold text-white mb-1">{item.name}</h4>
                    <Badge variant="outline" className={`mb-3 border-none bg-black/40 ${item.color}`}>{item.score}</Badge>
                    <p className="text-xs text-muted-foreground mt-auto leading-relaxed">{item.desc}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Bottom: Explainability Traceability */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
        >
          <Card className="glass-panel border-white/5 bg-black/60 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-8 opacity-5">
              <Search className="w-32 h-32" />
            </div>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Info className="w-5 h-5 text-indigo-400" />
                AI Logic & Explainability
              </CardTitle>
            </CardHeader>
            <CardContent className="relative z-10">
              <div className="p-6 rounded-xl border border-white/10 bg-white/[0.02] text-lg leading-relaxed">
                <span className="text-white/80">Decision Logic: </span>
                Rejected due to{" "}
                <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
                  <DialogTrigger asChild>
                    <button className="relative inline-flex items-center gap-1 font-bold text-red-400 hover:text-red-300 transition-colors border-b border-red-400/50 hover:border-red-300 border-dashed pb-0.5 group">
                      high litigation risk
                      <span className="absolute -top-3 -right-3 flex h-3 w-3">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-3 w-3 bg-red-500"></span>
                      </span>
                    </button>
                  </DialogTrigger>
                  <DialogContent className="max-w-3xl bg-card border-white/10 shadow-2xl p-0 overflow-hidden">
                    <DialogHeader className="p-6 pb-0 border-b border-white/5 bg-white/[0.02]">
                      <DialogTitle className="flex items-center gap-2 text-xl font-display">
                        <Scale className="w-5 h-5 text-indigo-400" />
                        e-Courts Traceability View
                      </DialogTitle>
                      <p className="text-sm text-muted-foreground mt-2 pb-4">
                        Source verification document pulled automatically by the AI Research Agent.
                      </p>
                    </DialogHeader>
                    <div className="p-6 bg-black/40">
                      {/* Wireframe of a court document */}
                      <div className="bg-white text-black p-8 rounded shadow-inner max-w-2xl mx-auto font-serif relative">
                        <div className="absolute top-4 right-4 border-2 border-red-600 text-red-600 font-bold transform rotate-12 px-4 py-1 text-2xl opacity-80 tracking-widest uppercase">
                          Source
                        </div>
                        <div className="text-center border-b-2 border-black/20 pb-4 mb-6">
                          <h2 className="text-xl font-bold uppercase">In the District Court of Pune</h2>
                          <p className="text-sm">Civil Suit No. 8991 of 2023</p>
                        </div>
                        <div className="space-y-4 text-sm leading-relaxed">
                          <p><strong>Between:</strong> Vendor Supplies Pvt Ltd (Plaintiff)</p>
                          <p><strong>And:</strong> Demo Company Ltd (Defendant)</p>
                          
                          <div className="my-6 p-4 border-2 border-red-500 bg-red-50 relative">
                            <div className="absolute -left-3 top-1/2 transform -translate-y-1/2">
                              <div className="bg-red-500 text-white rounded-full p-1 shadow-lg flex items-center justify-center">
                                <ArrowRight className="w-4 h-4" />
                              </div>
                            </div>
                            <p className="font-bold bg-yellow-200">
                              "The Defendant has defaulted on payments amounting to ₹2.4 Crores spanning a period of 14 months, leading to severe financial distress..."
                            </p>
                          </div>
                          
                          <p><strong>Status:</strong> Summons issued. Next hearing scheduled for 14th Nov 2023.</p>
                          
                          <div className="mt-8 pt-8 border-t border-black/10 flex justify-between items-center text-xs opacity-50">
                            <span>Extracted from e-Courts Portal API</span>
                            <span>Timestamp: 2023-10-24 14:32:01 UTC</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </DialogContent>
                </Dialog>
                {" "}found in secondary research despite strong GST flows and fully backed collateral.
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </motion.div>
    </AppLayout>
  );
}
