import { useState } from "react";
import { AppLayout } from "@/components/layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ShieldAlert, Briefcase, Wallet, Building, FileSignature, Scale, Download, TrendingUp, AlertTriangle, Zap, Target, AlertCircle } from "lucide-react";
import { RiskGauge } from "@/components/risk-gauge";

export default function Output() {
  const [dialogOpen, setDialogOpen] = useState(false);

  const downloadPDF = () => {
    const element = document.createElement("div");
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; color: #333;">
  
    <div style="text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px;">
      <h1 style="margin: 0; color: #003366; font-size: 24px; font-weight: bold;">AI-BACKED INVESTMENT & ASSESSMENT REPORT</h1>
      <p style="margin: 5px 0 0 0; color: #666;">Generated by: CredSight Reasoning Engine | Date: 11-March-2026</p>
    </div>
    
    <div style="display: flex; gap: 20px; margin-bottom: 30px; font-size: 14px;">
      <div style="flex: 1; background: #f9f9f9; padding: 15px; border: 1px solid #ddd; border-radius: 4px;">
        <h4 style="margin: 0 0 10px 0; color: #003366; border-bottom: 1px solid #ccc; padding-bottom: 5px;">Entity Onboarding Details</h4>
        <div style="margin: 5px 0;"><strong>Name:</strong> Apex Manufacturing Pvt. Ltd.</div>
        <div style="margin: 5px 0;"><strong>CIN:</strong> U28900MH2019PTC321456</div>
        <div style="margin: 5px 0;"><strong>PAN:</strong> ABCDE1234F</div>
        <div style="margin: 5px 0;"><strong>Sector:</strong> Manufacturing</div>
        <div style="margin: 5px 0;"><strong>Turnover:</strong> ₹150 Crores</div>
      </div>
      <div style="flex: 1; background: #f9f9f9; padding: 15px; border: 1px solid #ddd; border-radius: 4px;">
        <h4 style="margin: 0 0 10px 0; color: #003366; border-bottom: 1px solid #ccc; padding-bottom: 5px;">Requested Loan Details</h4>
        <div style="margin: 5px 0;"><strong>Type:</strong> Working Capital</div>
        <div style="margin: 5px 0;"><strong>Amount:</strong> ₹50 Crores</div>
        <div style="margin: 5px 0;"><strong>Tenure:</strong> 36 Months</div>
        <div style="margin: 5px 0;"><strong>Expected Interest:</strong> 9.0%</div>
      </div>
    </div>
    
    <div style="border-left: 5px solid #f4a460; background: #fff8f0; padding: 20px; margin-bottom: 30px;">
      <h3 style="margin: 0 0 15px 0; color: #003366;">Recommendation: <span style="color: #f4a460; font-weight: bold;">PARTIAL APPROVAL</span></h3>
      <div style="display: flex; gap: 40px;">
        <div style="margin: 5px 0;"><strong>Approved Limit:</strong> ₹35 Crores</div>
        <div style="margin: 5px 0;"><strong>Recommended Interest:</strong> 9.5%</div>
      </div>
    </div>
    
    <h3 style="color: #003366; margin-bottom: 15px; border-bottom: 1px solid #ddd; padding-bottom: 10px;">🧠 AI Reasoning Engine (Triangulation Output)</h3>
    <div style="background: #e6f4ea; border: 1px solid #ceead6; padding: 15px; margin-bottom: 30px; border-radius: 4px; font-size: 14px; color: #137333;">
      <p style="margin: 0;">Triangulation of extracted ALM data reveals a short-term liquidity mismatch. Secondary research (e-Courts) flags pending vendor litigation, confirming a cautious lending stance despite strong operational turnover. Recommended limit reduced to ₹35Cr.</p>
    </div>
    
    <h3 style="color: #003366; margin-bottom: 15px; border-bottom: 1px solid #ddd; padding-bottom: 10px;">Comprehensive GenAI SWOT Analysis</h3>
    <div style="display: flex; flex-wrap: wrap; gap: 15px; margin-bottom: 30px;">
      <div style="flex: 1 1 45%; border-top: 3px solid #1a73e8; background: #f8f9fa; padding: 15px; border-radius: 0 0 4px 4px;">
        <h4 style="margin: 0 0 10px 0; color: #1a73e8; font-size: 14px;">S - Strengths</h4>
        <p style="margin: 0; font-size: 13px; line-height: 1.5;">Consistent YoY revenue growth extracted from Annual Reports; robust Shareholding Pattern with 70% promoter retention.</p>
      </div>
      <div style="flex: 1 1 45%; border-top: 3px solid #e53935; background: #f8f9fa; padding: 15px; border-radius: 0 0 4px 4px;">
        <h4 style="margin: 0 0 10px 0; color: #e53935; font-size: 14px;">W - Weaknesses</h4>
        <p style="margin: 0; font-size: 13px; line-height: 1.5;">Asset-Liability Management (ALM) mapping indicates short-term cash flow constraints over the next 2 quarters.</p>
      </div>
      <div style="flex: 1 1 45%; border-top: 3px solid #34a853; background: #f8f9fa; padding: 15px; border-radius: 0 0 4px 4px;">
        <h4 style="margin: 0 0 10px 0; color: #34a853; font-size: 14px;">O - Opportunities</h4>
        <p style="margin: 0; font-size: 13px; line-height: 1.5;">Pre-cognitive secondary analysis shows favorable macro trends and new government subsidies for the manufacturing sector.</p>
      </div>
      <div style="flex: 1 1 45%; border-top: 3px solid #fbbc04; background: #f8f9fa; padding: 15px; border-radius: 0 0 4px 4px;">
        <h4 style="margin: 0 0 10px 0; color: #b08d00; font-size: 14px;">T - Threats</h4>
        <p style="margin: 0; font-size: 13px; line-height: 1.5;">Pending legal disputes identified via web scraping (e-Courts); potential headwinds from shifting RBI repo rates.</p>
      </div>
    </div>
    
    <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; font-size: 12px; color: #666;">
      <p style="margin: 0; font-family: monospace; font-weight: bold; font-size: 13px; color: #0066cc;">[DIGITALLY VERIFIED BY AI]</p>
      <div style="display: flex; justify-content: space-between; margin-top: 20px;">
        <div>
          <p style="margin: 0;">_____________________</p>
          <p style="margin: 5px 0 0 0; font-weight: bold; color: #333;">CredSight AI Engine</p>
        </div>
        <div style="text-align: right;">
          <p style="margin: 0;">_____________________</p>
          <p style="margin: 5px 0 0 0; color: #333;">Human Credit Manager<br/>Sign-off</p>
        </div>
      </div>
    </div>

  </div>
    `;
    
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    
    canvas.width = 800;
    canvas.height = 1200;
    
    const printWindow = window.open("", "", "height=800,width=800");
    if (printWindow) {
      printWindow.document.write(element.innerHTML);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const fiveCsData = [
    {
      name: "Character",
      rating: "Low",
      icon: ShieldAlert,
      color: "text-red-500",
      bgColor: "bg-red-500/10",
      borderColor: "border-red-500/30"
    },
    {
      name: "Capacity",
      rating: "Moderate",
      icon: Building,
      color: "text-orange-500",
      bgColor: "bg-orange-500/10",
      borderColor: "border-orange-500/30"
    },
    {
      name: "Capital",
      rating: "Strong",
      icon: Wallet,
      color: "text-emerald-500",
      bgColor: "bg-emerald-500/10",
      borderColor: "border-emerald-500/30"
    },
    {
      name: "Collateral",
      rating: "Strong",
      icon: FileSignature,
      color: "text-emerald-500",
      bgColor: "bg-emerald-500/10",
      borderColor: "border-emerald-500/30"
    },
    {
      name: "Conditions",
      rating: "Poor",
      icon: AlertCircle,
      color: "text-red-500",
      bgColor: "bg-red-500/10",
      borderColor: "border-red-500/30"
    }
  ];

  const swotData = [
    { 
      category: "Strengths", 
      icon: TrendingUp, 
      color: "text-emerald-500",
      bgColor: "bg-emerald-500/10",
      borderColor: "border-emerald-500/30",
      items: [
        "Strong borrowing profile and consistent portfolio performance",
        "Healthy equity retention and YoY profit margins"
      ]
    },
    { 
      category: "Weaknesses", 
      icon: AlertTriangle, 
      color: "text-red-500",
      bgColor: "bg-red-500/10",
      borderColor: "border-red-500/30",
      items: [
        "High asset-liability mismatch in the short term (ALM data)",
        "Factory operating at 40% capacity during site visit"
      ]
    },
    { 
      category: "Opportunities", 
      icon: Target, 
      color: "text-blue-500",
      bgColor: "bg-blue-500/10",
      borderColor: "border-blue-500/30",
      items: [
        "Favorable macro trends in the entity's sector",
        "New RBI initiatives supporting manufacturing growth"
      ]
    },
    { 
      category: "Threats", 
      icon: Zap, 
      color: "text-amber-500",
      bgColor: "bg-amber-500/10",
      borderColor: "border-amber-500/30",
      items: [
        "Pending legal disputes found via secondary research",
        "Regulatory headwinds in sector operations"
      ]
    },
  ];

  return (
    <AppLayout>
      <div className="space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <Badge variant="outline" className="mb-3">Recommendation Engine</Badge>
            <h1 className="text-2xl sm:text-3xl font-bold mb-2">Credit Appraisal Output</h1>
            <p className="text-sm sm:text-base text-muted-foreground">Final ML-based recommendation with explainability.</p>
          </div>
          <Button
            onClick={downloadPDF}
            variant="outline"
            className="gap-2 w-full sm:w-auto"
            data-testid="button-download-pdf"
          >
            <Download className="w-4 h-4" />
            <span className="hidden sm:inline">Download Assessment Report</span>
            <span className="sm:hidden">Report</span>
          </Button>
        </div>

        <Card className="card-simple border-red-500/30 bg-red-500/5">
          <CardContent className="p-4 sm:p-8 text-center">
            <div className="mb-6">
              <p className="text-xs sm:text-sm text-muted-foreground mb-2">FINAL DECISION</p>
              <h2 className="text-2xl sm:text-4xl font-bold mb-4">
                <span className="block sm:inline">RECOMMENDATION:</span> <span className="text-red-500">REJECT</span>
              </h2>
              <div className="flex flex-col sm:flex-row justify-center gap-4 sm:gap-8">
                <div>
                  <p className="text-xs text-muted-foreground">Suggested Limit</p>
                  <p className="text-lg sm:text-xl font-bold text-muted-foreground line-through">₹5.00 Cr</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Interest Rate</p>
                  <p className="text-lg sm:text-xl font-bold text-muted-foreground">N/A</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="card-simple">
          <CardHeader>
            <CardTitle className="text-sm sm:text-base">Overall Risk Assessment</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center py-6 sm:py-8 px-4">
            <div className="w-full max-w-xs">
              <RiskGauge score={72} label="Risk Score" data-testid="gauge-risk-score" />
            </div>
          </CardContent>
        </Card>

        <div className="space-y-4">
          <h3 className="text-base sm:text-lg font-semibold mb-3">Five Cs Assessment</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 sm:gap-4">
            {fiveCsData.map((item) => (
              <Card key={item.name} className={`card-simple border ${item.borderColor} ${item.bgColor} flex flex-col items-center text-center p-4 sm:p-6`}>
                <item.icon className={`w-8 h-8 sm:w-10 sm:h-10 ${item.color} mb-3`} />
                <CardTitle className="text-sm mb-3">{item.name}</CardTitle>
                <Badge variant="outline" className="mt-auto">{item.rating}</Badge>
              </Card>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-base sm:text-lg font-semibold mb-3">SWOT Analysis</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {swotData.map((swot) => (
              <Card key={swot.category} className={`card-simple border ${swot.borderColor} ${swot.bgColor}`}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-sm">
                    <swot.icon className={`w-5 h-5 ${swot.color}`} />
                    {swot.category}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2 text-xs sm:text-sm">
                    {swot.items.map((item, i) => (
                      <li key={i} className="flex gap-2">
                        <span className="text-primary font-bold mt-0.5">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        <Card className="card-simple">
          <CardHeader>
            <CardTitle className="text-base">AI Explainability</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">
              Rejected due to{" "}
              <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
                <DialogTrigger asChild>
                  <button className="font-bold text-red-500 hover:text-red-400 border-b border-red-500 hover-dim">
                    high litigation risk
                  </button>
                </DialogTrigger>
                <DialogContent className="max-w-2xl">
                  <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                      <Scale className="w-4 h-4" /> Court Document
                    </DialogTitle>
                  </DialogHeader>
                  <div className="bg-white text-black p-6 rounded text-sm space-y-3 max-h-[400px] overflow-y-auto">
                    <h3 className="font-bold text-center">District Court of Pune - Civil Suit 8991/2023</h3>
                    <div className="border-l-4 border-red-500 pl-4 py-2 bg-red-50">
                      <p className="font-bold">Plaintiff:</p>
                      <p>Vendor Supplies Pvt Ltd vs Demo Company Ltd</p>
                    </div>
                    <div className="border-l-4 border-red-500 pl-4 py-2 bg-yellow-50">
                      <p className="font-bold text-red-600">Claim: ₹2.4 Crores outstanding payment</p>
                      <p className="text-sm">14 months default period</p>
                    </div>
                    <p className="text-xs text-gray-600">Status: Pending Hearing | Extracted: e-Courts Portal API</p>
                  </div>
                </DialogContent>
              </Dialog>
              {" "}found in secondary research, despite strong GST flows.
            </p>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
