import { useState } from "react";
import { AppLayout } from "@/components/layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Download, TrendingUp, AlertTriangle, Zap, Target } from "lucide-react";
import { RiskGauge } from "@/components/risk-gauge";

const mockData = {
  dateGenerated: "12-March-2026",
  entityDetails: {
    name: "Vivriti Capital Limited",
    cin: "U65929TN2017PLC117196",
    pan: "AABCV1234F",
    sector: "Mid-Market Corporate NBFC",
    turnover: "₹7,000+ Crores (AUM)",
  },
  loanDetails: {
    type: "Working Capital Facility",
    requestedAmount: "₹100 Crores",
    tenure: "24 Months",
    expectedInterest: "9.25%",
  },
  decisionStatus: "APPROVED",
  decisionColor: "#10b981",
  approvedLimit: "₹100 Crores",
  interestRate: "9.25%",
  reasoningEngine:
    "Extraction from Vivriti Capital's Annual Report confirms exceptional asset quality with gross NPAs maintained well below industry averages. Their proprietary tech-enabled underwriting and diversified mid-market exposure provide strong downside protection. Capital adequacy remains robust. Full limit approved.",
  swotAnalysis: {
    strengths:
      "Highly diversified mid-market corporate portfolio; industry-leading proprietary risk assessment models; strong institutional backing and equity base.",
    weaknesses:
      "Relatively higher cost of funds compared to top-tier legacy banks operating in the same corporate segment.",
    opportunities:
      "Significant growth potential in co-lending partnerships and supply chain finance leveraging digital public infrastructure.",
    threats:
      "Intensifying competition from larger legacy banks expanding into the mid-market corporate lending space.",
  },
};

export default function Output() {
  const [_unused] = useState(false);

  const downloadPDF = () => {
    const element = document.createElement("div");
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; color: #333;">
        <div style="text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="margin: 0; color: #003366; font-size: 24px; font-weight: bold;">AI-BACKED INVESTMENT &amp; ASSESSMENT REPORT</h1>
          <p style="margin: 5px 0 0 0; color: #666;">Generated by: CredSight AI Engine</p>
        </div>
        
        <div style="display: flex; justify-content: space-between; margin-bottom: 30px;">
          <div><strong>Borrower:</strong> ${mockData.entityDetails.name}</div>
          <div><strong>Date:</strong> ${mockData.dateGenerated}</div>
        </div>

        <div style="margin-bottom: 20px; font-size: 14px;">
          <div style="margin: 5px 0;"><strong>CIN:</strong> ${mockData.entityDetails.cin}</div>
          <div style="margin: 5px 0;"><strong>PAN:</strong> ${mockData.entityDetails.pan}</div>
          <div style="margin: 5px 0;"><strong>Sector:</strong> ${mockData.entityDetails.sector}</div>
          <div style="margin: 5px 0;"><strong>AUM / Turnover:</strong> ${mockData.entityDetails.turnover}</div>
        </div>

        <div style="margin-bottom: 20px; font-size: 14px;">
          <div style="margin: 5px 0;"><strong>Loan Type:</strong> ${mockData.loanDetails.type}</div>
          <div style="margin: 5px 0;"><strong>Requested Amount:</strong> ${mockData.loanDetails.requestedAmount}</div>
          <div style="margin: 5px 0;"><strong>Tenure:</strong> ${mockData.loanDetails.tenure}</div>
        </div>
        
        <div style="border-left: 5px solid ${mockData.decisionColor}; background: #f0fdf4; padding: 20px; margin-bottom: 30px;">
          <h3 style="margin: 0 0 15px 0; color: #003366;">Executive AI Recommendation: <span style="color: ${mockData.decisionColor}; font-weight: bold;">${mockData.decisionStatus}</span></h3>
          <div style="margin: 5px 0;"><strong>Requested Limit:</strong> ${mockData.loanDetails.requestedAmount}</div>
          <div style="margin: 5px 0;"><strong>Approved Limit:</strong> ${mockData.approvedLimit}</div>
          <div style="margin: 5px 0;"><strong>Interest Rate:</strong> ${mockData.interestRate}</div>
        </div>
        
        <h3 style="color: #003366; margin-bottom: 15px; border-bottom: 1px solid #ddd; padding-bottom: 10px;">Explainability &amp; Decision Logic</h3>
        <div style="background: #f0f4ff; padding: 15px; margin-bottom: 30px; border-radius: 4px; font-size: 14px;">
          <p style="margin: 0;">${mockData.reasoningEngine}</p>
        </div>

        <h3 style="color: #003366; margin-bottom: 15px; border-bottom: 1px solid #ddd; padding-bottom: 10px;">SWOT Analysis</h3>
        <ul style="line-height: 1.8; font-size: 14px;">
          <li><strong>Strengths:</strong> ${mockData.swotAnalysis.strengths}</li>
          <li><strong>Weaknesses:</strong> ${mockData.swotAnalysis.weaknesses}</li>
          <li><strong>Opportunities:</strong> ${mockData.swotAnalysis.opportunities}</li>
          <li><strong>Threats:</strong> ${mockData.swotAnalysis.threats}</li>
        </ul>
        
        <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; font-size: 12px; color: #666;">
          <p style="margin: 0; text-transform: uppercase; color: #0066cc;">Digitally Verified by AI</p>
          <div style="display: flex; justify-content: space-between; margin-top: 20px;">
            <div><p style="margin: 0;">_____________________</p><p style="margin: 5px 0 0 0;">CredSight AI Engine</p></div>
            <div style="text-align: right;"><p style="margin: 0;">_____________________</p><p style="margin: 5px 0 0 0;">Human Credit Manager<br/>Sign-off</p></div>
          </div>
        </div>
      </div>
    `;

    const printWindow = window.open("", "", "height=800,width=800");
    if (printWindow) {
      printWindow.document.write(element.innerHTML);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const swotData = [
    {
      category: "Strengths",
      icon: TrendingUp,
      color: "text-emerald-500",
      bgColor: "bg-emerald-500/10",
      borderColor: "border-emerald-500/30",
      items: mockData.swotAnalysis.strengths.split(";").map((s) => s.trim()),
    },
    {
      category: "Weaknesses",
      icon: AlertTriangle,
      color: "text-red-500",
      bgColor: "bg-red-500/10",
      borderColor: "border-red-500/30",
      items: [mockData.swotAnalysis.weaknesses],
    },
    {
      category: "Opportunities",
      icon: Target,
      color: "text-blue-500",
      bgColor: "bg-blue-500/10",
      borderColor: "border-blue-500/30",
      items: mockData.swotAnalysis.opportunities.split("and").map((s) => s.trim()),
    },
    {
      category: "Threats",
      icon: Zap,
      color: "text-amber-500",
      bgColor: "bg-amber-500/10",
      borderColor: "border-amber-500/30",
      items: [mockData.swotAnalysis.threats],
    },
  ];

  return (
    <AppLayout>
      <div className="space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <Badge variant="outline" className="mb-3">Recommendation Engine</Badge>
            <h1 className="text-2xl sm:text-3xl font-bold mb-2">Credit Appraisal Output</h1>
            <p className="text-sm sm:text-base text-muted-foreground">Final ML-based recommendation with explainability.</p>
          </div>
          <Button
            onClick={downloadPDF}
            variant="outline"
            className="gap-2 w-full sm:w-auto"
            data-testid="button-download-pdf"
          >
            <Download className="w-4 h-4" />
            <span className="hidden sm:inline">Download Assessment Report</span>
            <span className="sm:hidden">Report</span>
          </Button>
        </div>

        <Card className="card-simple border-emerald-500/30 bg-emerald-500/5">
          <CardContent className="p-4 sm:p-8 text-center">
            <div className="mb-6">
              <p className="text-xs sm:text-sm text-muted-foreground mb-2">FINAL DECISION</p>
              <h2 className="text-2xl sm:text-4xl font-bold mb-4">
                <span className="block sm:inline">RECOMMENDATION:</span>{" "}
                <span style={{ color: mockData.decisionColor }}>{mockData.decisionStatus}</span>
              </h2>
              <div className="flex flex-col sm:flex-row justify-center gap-4 sm:gap-8">
                <div>
                  <p className="text-xs text-muted-foreground">Approved Limit</p>
                  <p className="text-lg sm:text-xl font-bold" style={{ color: mockData.decisionColor }}>
                    {mockData.approvedLimit}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Interest Rate</p>
                  <p className="text-lg sm:text-xl font-bold" style={{ color: mockData.decisionColor }}>
                    {mockData.interestRate}
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="card-simple">
          <CardHeader>
            <CardTitle className="text-sm sm:text-base">Overall Risk Assessment</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center py-6 sm:py-8 px-4">
            <div className="w-full max-w-xs">
              <RiskGauge score={28} label="Risk Score" data-testid="gauge-risk-score" />
            </div>
          </CardContent>
        </Card>

        <div className="space-y-4">
          <h3 className="text-base sm:text-lg font-semibold mb-3">SWOT Analysis</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {swotData.map((swot) => (
              <Card key={swot.category} className={`card-simple border ${swot.borderColor} ${swot.bgColor}`}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-sm">
                    <swot.icon className={`w-5 h-5 ${swot.color}`} />
                    {swot.category}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2 text-xs sm:text-sm">
                    {swot.items.map((item, i) => (
                      <li key={i} className="flex gap-2">
                        <span className="text-primary font-bold mt-0.5">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        <Card className="card-simple">
          <CardHeader>
            <CardTitle className="text-base">AI Explainability</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">{mockData.reasoningEngine}</p>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
